# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue
  theme_day: minimal
  theme_night: minimal
  fontsize: L

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'PhD candidate in robotics, BMW AI Robotics and TU-Eindhoven'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "right"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Pietro Dardano"

# Site footer
footer:
  copyright:
    notice: '© {year}. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  avatar:
    gravatar: false
    shape: circle
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions
extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true